### ISSUE TITLE
[FEATURE] Retrieve only the first category id

### ISSUE THREAD

**Issue by sebastianherrera** [Vinai/VinaiKopp_ProductCategories#5]
Dear Vinai, i checked CategoryList.php code and you have a protected variable $_firstProductCat; I try to create a function to retrieve only the first category id but with no success. I believe that could be interesting for css manipulation, as an example to display a particular layout/buttons colors if it has a particular parent category like:

```css
body.cat-40 #hero .title {
    background: none repeat-x scroll 0 top #e24913;
}
body.cat-40 = cat-[firstcategoryid]
```

In my case Im using the following code in product - view

```php
<?php $currentCat = Mage::registry('current_category'); ?>
<?php if (isset($currentCat) ) { ?>
    <?php $exp = explode("/", $currentCat->getPath());?>
<?php } { ?>
    <?php $exp = explode("/", '/1/0/10');?>
<?php } ?>
```

but its not working in all the cases. thanks in advance.
brgds
sebastian.
